
SHELL = /bin/sh

include ${PETSC_DIR}/${PETSC_ARCH}/conf/petscvariables
include ${PETSC_DIR}/conf/variables
PCC = ${MPI_DIR}/bin/mpicxx

CFLAGS = -g -DDEBUG -DPETSC_USE_LOG  
#CFLAGS = -O3 -DPETSC_USE_LOG

include ./makefileCore

